Add posion flower prefab
sysut2020/monster-hunt pull request #102
Opened 2020-04-15 12:36 UTC by freshfish70

2020-04-15 12:39 UTC, TrygveJW approved these changes

2020-04-15 13:12 UTC, sanderhurlen requested changes
Fabelaktig! Men skulle helst sett det var enklere å se at planta har skada playern! For eks: lyd eller rød blink

2020-04-17 13:37 UTC, freshfish70 commented
Det du vil endre på Hurle, er fikset i en ny PR som fikser en del andre ting relatert til skader.

2020-04-17 13:41 UTC, perkynades approved these changes

2020-04-17 13:43 UTC, merged