Scoreboard available on Main menu
sysut2020/monster-hunt pull request #104
Opened 2020-04-15 13:44 UTC by sanderhurlen

2020-04-15 15:22 UTC, TrygveJW requested changes

2020-04-15 15:22 UTC, TrygveJW commented on unityfiles/Assets/ScoreBoard.cs
> +    }
fjern denne unødvendig og skaper feilmeldinger

2020-04-15 15:22 UTC, TrygveJW commented on unityfiles/Assets/ScoreBoard.cs
> +        }
hvis en persjon går ut av en level eller taper paa level > 1 vil denne ikke blokke å score vil bli etterspurt

2020-04-15 15:39 UTC, sanderhurlen commented on unityfiles/Assets/ScoreBoard.cs
> +        }
Den har jeg ikke sett! takk

2020-04-16 13:37 UTC, sanderhurlen commented
- Scoreboard tilgjengelig på menyen
- Fiksa en bug som kom ved onClick event i script -> denne er nå satt manuelt på button i scenen
- scoreboard prefab skal nå se nogenlunde lik ut på både meny og scoreboard scenene

2020-04-17 13:39 UTC, freshfish70 approved these changes

2020-04-17 13:52 UTC, TrygveJW approved these changes

2020-04-17 14:07 UTC, merged