Game over events
sysut2020/monster-hunt pull request #30
Opened 2020-02-12 07:54 UTC by spiftire

Created a `GameManager` to handle game states. It will fire an `OnEndGame` event when game ends.

Also setup different support files and methods to help with this implementation

2020-02-12 08:27 UTC, perkynades approved these changes

2020-02-12 10:20 UTC, freshfish70 requested changes

2020-02-12 10:20 UTC, freshfish70 commented on unityfiles/Assets/Scripts/Game/Player/Player.cs
>      }
Håndteres av HealthController; Player må implementere IDamageble. 
Da vil HealthController calle metoden Dead(); som blir implementert når livet er 0

2020-02-12 10:20 UTC, freshfish70 commented on unityfiles/Assets/Scripts/Game/Player/Player.cs
> +    public static event PlayerDeadHandler OnPlayerDead;
Kan endres til `public static EventHandler OnPlayerDead;`
Gir fordel med at den som Invoker eventet på gi seg selv med; slik at det er lett å håntdere hvem som kaller event ved evt feilsøking o.l

2020-02-12 10:20 UTC, freshfish70 commented on unityfiles/Assets/Scripts/Game/Player/Player.cs
> +[RequireComponent(typeof(HealthController))]
Kan fjernes vist du implementerer IDamageble

2020-02-12 10:20 UTC, freshfish70 commented on unityfiles/Assets/Scripts/Game/Player/Player.cs
> +    private const string DAMAGE_STRING = "Damage";
Lage en konstant klasse med navne for Animasjons triggerene o.l ?

2020-02-13 07:12 UTC, freshfish70 approved these changes

2020-02-13 07:12 UTC, merged