Pull request for item collection
sysut2020/monster-hunt pull request #34
Opened 2020-02-17 16:38 UTC by perkynades

2020-02-17 18:19 UTC, TrygveJW requested changes
Dette er ikke bra nokk Sjekk i allefall at koden er i nerheten av å virke før du merger inn

2020-02-17 18:19 UTC, TrygveJW commented on unityfiles/Assets/Scripts/CollectibleSpawner.cs
> +                LetterController le = Instantiate(letterCollectable);
side note her "le" er ikke en brukbar forkortelse for **L**etter**C**ontroller, spesielt siden det er noe som heter letter i denne konteksten.

2020-02-17 18:19 UTC, TrygveJW commented on unityfiles/Assets/Scripts/Game/Player/PlayerInventory.cs
> +        this.money += value;
hvis du bytte en parameter i en fungsjon så e det viktig å husk og bytt i kommentaren til fungsjonen

2020-02-17 18:19 UTC, TrygveJW commented on unityfiles/Assets/Scripts/Events/CollecableEvents.cs
> +}
nå grunn til at dem her ikke eksistere som statiske event handlera i selve Letter og Coin

2020-02-17 18:19 UTC, TrygveJW commented on unityfiles/Assets/Scripts/Game/Collectables/CollectablesCollectionAnimation.cs
> +}
den her funke ikke i det hele tatt til mæ æ får en UnassignedReferenceException. Hvorfor tar du ikke bara å bruke nåkka som vector3.interpolate(enemyKilledTransform, guiMålplass.toWorldCords, økendefraksjon) istedet for og bruk et helt bibliotek

2020-02-17 18:19 UTC, TrygveJW commented on unityfiles/Assets/Scripts/Game/Collectables/CollectablesCollectionAnimation.cs
> +}
har ikke sotte mæ inn i iTween men e du sikker på at den her handle at spilleren bevege sæ etter målet e skutt eller vil den da gå mot intet

2020-02-17 18:19 UTC, TrygveJW commented on unityfiles/Assets/Scripts/Game/Collectables/Coin.cs
> +        }
hvorfor? det her e jo coin scriptet så en sjekk på om coin scripte finnes e totalt unødvendig

2020-02-17 18:19 UTC, TrygveJW commented on unityfiles/Assets/Scripts/CollectibleSpawner.cs
> +                LetterController le = Instantiate(letterCollectable);
ok endelig fant æ det ut. Av en eller annen rar grunn får du låv til og dra et game object med et LetterController script til det private feltet letter controller. Dette er feil måte å jøre det på. Bytt feltet til og ta i mot prefaben til LetterPlateTing

2020-02-17 18:19 UTC, TrygveJW commented on unityfiles/Assets/Scripts/CollectibleSpawner.cs
> +                Letter letterToAddToInventory = this.gameObject.GetComponent<Letter>();
this.gameobject gir det tomme GO som colectable spawner ligger i. der er det ingen Letter script

2020-02-17 18:19 UTC, TrygveJW commented on unityfiles/Assets/Scripts/CollectibleSpawner.cs
> +                letterToAddToInventory.LetterString = letter;
siden den over er null vil denne krasje og brenne

2020-02-17 18:19 UTC, TrygveJW commented on unityfiles/Assets/Scripts/CollectibleSpawner.cs
> +                collectible.name = "Letter " + letter;
Ikke det at vi skal bruke navnene frammover, men ta for guds skyld og bruk _ istedet for space som sepratør

2020-02-17 18:19 UTC, TrygveJW commented on unityfiles/Assets/Scripts/Game/Collectables/Coin.cs
> +        }
pluss at du collecter med en gang og ikke når den når endepungtet som er de vi ble enige om

2020-02-17 18:19 UTC, TrygveJW commented on unityfiles/Assets/Scripts/Game/Collectables/Letter.cs
> +        }
som nevnt over å finne noe etter navn er ikke en god måte

2020-02-17 18:19 UTC, TrygveJW commented on unityfiles/Assets/Scripts/Game/Collectables/Letter.cs
> +        }
men siden at sjekken her ikke trenger og finnes er det streng tatt ikke et problem

2020-02-17 18:19 UTC, TrygveJW commented on unityfiles/Assets/Scripts/CollectibleSpawner.cs
> +                collectible.name = "Coin";
hvis du skal bruke et system som sjekker navn ved initsialisering er det lurt og sette navn først

2020-02-17 18:31 UTC, freshfish70 commented on unityfiles/Assets/Scripts/Events/CollecableEvents.cs
> +}
Ditta e mitt styr ;D midlertidig implementert for å få events

2020-02-18 17:30 UTC, freshfish70 commented
Lukker denne da den kommer sammen med min merge; siden de går litt i lag :D Elton var enig

2020-02-18 17:30 UTC, closed without merging