Combining all the work that has been added to dev
sysut2020/monster-hunt pull request #9
Opened 2020-01-24 11:18 UTC by spiftire

This is a work in progress. All that we want to show to the customer on Monday can be added to this branch

2020-01-28 13:36 UTC, sanderhurlen approved these changes

2020-01-28 14:03 UTC, TrygveJW requested changes
Skal vi ha støtte for hele det crouch oplegget ?
hvis ikke burde det fjernes siden det potensielt kan skape mye problemer

2020-01-28 14:03 UTC, TrygveJW commented on unityfiles/Assets/Scripts/CharacterController2D.cs
> +	[SerializeField] private Collider2D crouchDisableCollider;
burde endre disse til 
[serie...]
var

[serie...]
var

mere oversiktelig og mindre blokk med tekst aktig

2020-01-28 14:03 UTC, TrygveJW commented on unityfiles/Assets/Scripts/PlayerMovement.cs
>          set => jump = value;
bedre med isJumping

2020-01-29 11:02 UTC, spiftire commented on unityfiles/Assets/Scripts/CharacterController2D.cs
> +	[SerializeField] private Collider2D crouchDisableCollider;
Endret

2020-01-29 11:19 UTC, spiftire commented
Vi støtter crouch nå. Kan evt ta det ut senere

2020-01-29 11:31 UTC, merged

2020-01-29 11:32 UTC, TrygveJW approved these changes
Ser ok ut. Mye i Character controller 2d som ikke er helt idielt